# Generated by Django 3.0.5 on 2022-01-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20220128_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_set',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='choices', to='quiz.Question'),
        ),
    ]
