# Generated by Django 3.0.5 on 2022-01-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20220131_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(blank=True, to='quiz.Options'),
        ),
        migrations.AlterField(
            model_name='question_set',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quiz.Question'),
        ),
    ]
