# Generated by Django 3.0.5 on 2022-01-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20220131_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='option',
        ),
        migrations.AddField(
            model_name='options',
            name='op1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='options',
            name='op2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='options',
            name='op3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='options',
            name='op4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
