# Generated by Django 3.0.5 on 2022-01-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20220131_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='op1',
        ),
        migrations.RemoveField(
            model_name='options',
            name='op2',
        ),
        migrations.RemoveField(
            model_name='options',
            name='op3',
        ),
        migrations.RemoveField(
            model_name='options',
            name='op4',
        ),
        migrations.AddField(
            model_name='options',
            name='option',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
